<a href="https://colab.research.google.com/github/khush-hii/Order-for-tanX.fi/blob/main/Order_Khushi_VIT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd

In [23]:
data = pd.read_csv("/Orders.csv")
data

,order_id,customer_id,order_date,product_id,product_name,product_price,quantity
0,101,121,2024-01-12,201,Product A,300,4
1,102,122,2024-01-15,210,Product Z,500,3
2,103,123,2024-02-06,203,Product C,200,2
3,104,124,2024-03-16,201,Product A,300,5
4,105,125,2024-05-27,209,Product Y,400,2
5,106,126,2024-06-11,203,Product C,200,6
6,107,127,2024-02-28,202,Product B,100,8
7,108,128,2024-03-04,204,Product D,600,2
8,109,129,2024-05-18,201,Product A,300,4
9,110,130,2024-07-24,204,Product D,600,1
10,111,131,2024-04-17,202,Product B,100,3
11,112,132,2024-04-03,210,Product Z,500,4
12,113,133,2024-06-15,209,Product Y,400,3
13,114,134,2024-04-27,203,Product C,200,4
14,115,135,2024-06-15,202,Product B,100,8
15,116,136,2024-03-24,201,Product A,300,3
16,117,137,2024-02-07,210,Product Z,500,4

 Computing the total revenue generated by the online store for each month in the dataset.

In [18]:
def total_revenue_by_month(data):
    data['order_date'] = pd.to_datetime(data['order_date'])
    data['month'] = data['order_date'].dt.to_period('M')
    revenue_by_month = data.groupby('month').apply(lambda x: (x['product_price'] * x['quantity']).sum())
    return revenue_by_month

revenue_by_month = total_revenue_by_month(data)
print("Total Revenue by Month:")
print(revenue_by_month)

Total Revenue by Month:
month
2024-01    2700
2024-02    3200
2024-03    3600
2024-04    3100
2024-05    2000
2024-06    3200
2024-07     600
Freq: M, dtype: int64

Computing the total revenue generated by each product in the dataset

In [27]:
def total_revenue_by_product(data):
    revenue_by_product = data.groupby(['product_id', 'product_name']).apply(lambda x: (x['product_price'] * x['quantity']).sum())
    return revenue_by_product

revenue_by_product = total_revenue_by_product(data)
print("\nTotal Revenue by Product:")
print(revenue_by_product)

Total Revenue by Product:
product_id  product_name
201         Product A       4800
202         Product B       1900
203         Product C       2400
204         Product D       1800
209         Product Y       2000
210         Product Z       5500
dtype: int64

 Computing the total revenue generated by each customer in the
dataset.

In [20]:
def total_revenue_by_customer(data):
    revenue_by_customer = data.groupby('customer_id').apply(lambda x: (x['product_price'] * x['quantity']).sum())
    return revenue_by_customer

revenue_by_customer = total_revenue_by_customer(data)
print("\nTotal Revenue by Customer:")
print(revenue_by_customer)

Total Revenue by Customer:
customer_id
121    1200
122    1500
123     400
124    1500
125     800
126    1200
127     800
128    1200
129    1200
130     600
131     300
132    2000
133    1200
134     800
135     800
136     900
137    2000
dtype: int64

Identify the top 10 customers by revenue generated.

In [21]:
def top_10_customers(revenue_by_customer):
    top_customers = revenue_by_customer.sort_values(ascending=False).head(10)
    return top_customers

top_customers = top_10_customers(revenue_by_customer)
print("\nTop 10 Customers by Revenue:")
print(top_customers)

Top 10 Customers by Revenue:
customer_id
137    2000
132    2000
124    1500
122    1500
128    1200
133    1200
121    1200
126    1200
129    1200
136     900
dtype: int64

Printing the results:

In [28]:

print("Total Revenue by Month:")
print(revenue_by_month)
print("\nTotal Revenue by Product:")
print(revenue_by_product)
print("\nTotal Revenue by Customer:")
print(revenue_by_customer)
print("\nTop 10 Customers by Revenue:")
print(top_customers)

Total Revenue by Month:
month
2024-01    2700
2024-02    3200
2024-03    3600
2024-04    3100
2024-05    2000
2024-06    3200
2024-07     600
Freq: M, dtype: int64

Total Revenue by Product:
product_id  product_name
201         Product A       4800
202         Product B       1900
203         Product C       2400
204         Product D       1800
209         Product Y       2000
210         Product Z       5500
dtype: int64

Total Revenue by Customer:
customer_id
121    1200
122    1500
123     400
124    1500
125     800
126    1200
127     800
128    1200
129    1200
130     600
131     300
132    2000
133    1200
134     800
135     800
136     900
137    2000
dtype: int64

Top 10 Customers by Revenue:
customer_id
137    2000
132    2000
124    1500
122    1500
128    1200
133    1200
121    1200
126    1200
129    1200
136     900
dtype: int64